### ISSUE TITLE
Not working under Redmine 2.6 ?

### ISSUE THREAD

**Issue by pyroit** [Restream/notify_custom_users#2]
Hi Team,
fist of all thank you for providing us with such brilliant plug-ins. 

Im using redmine 2.6  on Ubuntu 14.04. I installed the plug-in but I could not find any way to get this plug  set up. Since I have never uses this plug-in before I am not sure if it is not working under 2.6 or if I am just to stupid to find the options. 

The normal email notification works, also I tried to add some custom user fields but it did not happened any think when I set some user to it. 

Tank you very much
and have a nice day

**Comment by ChetWang** [comment]
Unfortunately, it's not working under 3.0.1 either.
The plugin is installed and is displayed in plugin setting in redmine. 
No errors  in production.log

**Comment by nodecarter** [comment]
The last version 1.0.2 has been tested with redmine 3.3.0
